query findAllQuotesByStatus($status: String!){
    findAllQuotesByStatus(status: $status){
        category
        id
        itemNumber
        poNumber
        stage
        status
        supplier
    }
}